# Generated by Django 5.1.8 on 2025-04-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20, unique=True)),
                ('work_id', models.CharField(blank=True, max_length=20, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=13, null=True)),
                ('asin', models.CharField(blank=True, max_length=20, null=True)),
                ('kindle_asin', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(max_length=255)),
                ('title_without_series', models.CharField(blank=True, max_length=255, null=True)),
                ('series', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('publication_month', models.IntegerField(blank=True, null=True)),
                ('publication_day', models.IntegerField(blank=True, null=True)),
                ('edition_information', models.CharField(blank=True, max_length=255, null=True)),
                ('format', models.CharField(blank=True, max_length=100, null=True)),
                ('num_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('is_ebook', models.BooleanField(default=False)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('image_url_large', models.URLField(blank=True, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('ratings_count', models.PositiveIntegerField(blank=True, null=True)),
                ('text_reviews_count', models.PositiveIntegerField(blank=True, null=True)),
                ('popular_shelves', models.JSONField(blank=True, null=True)),
                ('similar_books', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
