# Generated by Django 5.1.8 on 2025-05-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url_large',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
