# Generated by Django 5.1.9 on 2025-05-13 10:34

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_isbn_alter_book_isbn13')
    ]
    
    operations = [
        VectorExtension()
    ]
