# Generated by Django 5.1.9 on 2025-05-14 19:37

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_emotionclip_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_images/%Y/%m/%d/')),
                ('emotionclip_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['emotionclip_embedding'], name='emotionclip_idx'),
        ),
        migrations.AddIndex(
            model_name='userimage',
            index=models.Index(fields=['emotionclip_embedding'], name='user_image_emotionclip_idx'),
        ),
    ]
