services:
  db:
    image: timescale/timescaledb:latest-pg16     # ← includes timescaledb + pgvectorscale
    # load all vars from .env
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    ports: ["8000:8000"]
    depends_on: [db]
    volumes:  # hot-reload; remove in prod
      - .:/app

volumes:
  db_data:
